"""Generate paper/results.tex (LaTeX tables + number macros) from results/summary.json.

Run from the repo root:  .venv/bin/python paper/generate_tables.py
"""
import json
import os

RESULTS = "results"
OUT = os.path.join("paper", "results.tex")

METHOD_ORDER = ["baseline", "chemical-off", "fixed-schedule", "random-gate",
                "tag-only", "mod", "chemical"]
METHOD_NAMES = {
    "baseline": "Baseline",
    "chemical": "\\textbf{Chemical (ours)}",
    "chemical-off": "Chemical-off",
    "mod": "MoD (top-$k$)",
    "random-gate": "Random-gate",
    "fixed-schedule": "Fixed-schedule",
    "tag-only": "Tag-only",
}
BIN_NAMES = {
    "tagged": ["Easy", "Med", "Hard"],
    "mixed": ["1-dig", "2-dig", "3-dig", "4-dig"],
}


def fmt(m, s, scale=100, bold=False):
    body = f"{m * scale:.1f}$\\pm${s * scale:.1f}"
    return f"\\textbf{{{body}}}" if bold else body


def main():
    with open(os.path.join(RESULTS, "summary.json")) as f:
        summary = json.load(f)

    lines = ["% auto-generated by paper/generate_tables.py -- do not edit"]
    for task, tsummary in summary.items():
        if "chemical" not in tsummary or "baseline" not in tsummary:
            continue
        # best non-chemical accuracy for bolding
        lines.append(f"\n% ---- {task} ----")
        lines.append("\\begin{table}[t]")
        lines.append("\\centering")
        lines.append(f"\\caption{{{task.capitalize()} arithmetic: held-out answer accuracy "
                     "(mean $\\pm$ std over seeds), balanced accuracy (macro over difficulty "
                     "bins), and compute per token.}}")
        lines.append(f"\\label{{tab:{task}}}")
        lines.append("\\small")
        n_bins = len(BIN_NAMES[task])
        cols = "l" + "c" * (n_bins + 3)
        lines.append(f"\\begin{{tabular}}{{{cols}}}")
        lines.append("\\toprule")
        header = "Method & " + " & ".join(BIN_NAMES[task]) + \
                 " & Overall & Balanced & MFLOPs/tok \\\\"
        lines.append(header)
        lines.append("\\midrule")
        best_overall = max(
            (e["acc"]["mean"] for m, e in tsummary.items() if m != "chemical" and "acc" in e),
            default=0.0)
        for method in METHOD_ORDER:
            if method not in tsummary or "acc" not in tsummary[method]:
                continue
            e = tsummary[method]
            row = [METHOD_NAMES[method]]
            for b in range(n_bins):
                row.append(fmt(e["bin_acc"][b]["mean"], e["bin_acc"][b]["std"]))
            bold = method == "chemical" and e["acc"]["mean"] >= best_overall
            row.append(fmt(e["acc"]["mean"], e["acc"]["std"], bold=bold))
            row.append(fmt(e["balanced_acc"]["mean"], e["balanced_acc"]["std"], bold=bold))
            fl = e["flops_per_token"]
            row.append(f"{fl['mean'] / 1e6:.2f}$\\pm${fl['std'] / 1e6:.2f}")
            lines.append(" & ".join(row) + " \\\\")
            if "ttest_vs_chemical_acc" in e:
                lines.append(f"% t-test chemical vs {method}: "
                             f"t={e['ttest_vs_chemical_acc']['t']:.2f} "
                             f"p={e['ttest_vs_chemical_acc']['p']:.4f}")
        lines.append("\\bottomrule")
        lines.append("\\end{tabular}")
        lines.append("\\end{table}")

        # number macros for the text
        chem = tsummary["chemical"]
        base = tsummary["baseline"]
        pfx = task.capitalize()
        lines.append(f"\\newcommand{{\\{pfx}ChemAcc}}{{{chem['acc']['mean'] * 100:.1f}}}")
        lines.append(f"\\newcommand{{\\{pfx}BaseAcc}}{{{base['acc']['mean'] * 100:.1f}}}")
        lines.append(f"\\newcommand{{\\{pfx}ChemFlops}}{{{chem['flops_per_token']['mean'] / 1e6:.2f}}}")
        lines.append(f"\\newcommand{{\\{pfx}BaseFlops}}{{{base['flops_per_token']['mean'] / 1e6:.2f}}}")
        flop_save = 100 * (1 - chem["flops_per_token"]["mean"] / base["flops_per_token"]["mean"])
        lines.append(f"\\newcommand{{\\{pfx}FlopSave}}{{{flop_save:.0f}}}")
        if "entropy_pearson" in chem:
            lines.append(f"\\newcommand{{\\{pfx}EntPearson}}{{{chem['entropy_pearson']['mean']:.3f}}}")
            lines.append(f"\\newcommand{{\\{pfx}EntSpearman}}{{{chem['entropy_spearman']['mean']:.3f}}}")

    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
