"""Generate the RAAAI paper's comparison tables + number macros.

Reads:
  results/{task}/*.json                     baselines (6000-step runs)
  results-opt3b-full/{task}/predictor-supervised_seed*.json   ours (3K+3K)
  results-opt3b-s1-5k/tagged/predictor-supervised_seed*.json  ours (5K+3K tweak)
  results/correlations.json                 per-iteration correlations

Writes paper/results_raaai.tex and prints a text preview.
Run from repo root: .venv/bin/python paper/generate_tables_raaai.py
"""
import glob
import json
import os

BIN_LABELS = {"tagged": ["Easy", "Med", "Hard"],
              "mixed": ["1-dig", "2-dig", "3-dig", "4-dig"]}

METHODS = [
    ("baseline", "Baseline"),
    ("chemical-off", "Chemical-off"),
    ("fixed-schedule", "Fixed-schedule (0.5)"),
    ("mod", "MoD (top-$k$)"),
    ("chemical", "Chemical (entropy)"),
    ("random-gate", "Random-gate"),
    ("tag-only", "Tag-only"),
]


def load(pattern):
    runs = []
    for path in sorted(glob.glob(pattern)):
        with open(path) as f:
            runs.append(json.load(f))
    return runs


def ms(vals):
    import statistics as st
    vals = [v for v in vals if v is not None]
    if not vals:
        return None, None
    m = sum(vals) / len(vals)
    s = st.stdev(vals) if len(vals) > 1 else 0.0
    return m, s


def spread(run):
    gb = run["final"].get("gate_by_bin")
    if not gb or gb[0] is None or gb[-1] is None:
        return None
    return gb[-1] - gb[0]


def row_stats(runs):
    acc_m, acc_s = ms([r["final"]["acc"] for r in runs])
    bal_m, bal_s = ms([r["final"]["balanced_acc"] for r in runs])
    fl_m, fl_s = ms([r["final"]["flops_per_token"] / 1e6 for r in runs])
    sp_m, sp_s = ms([spread(r) for r in runs])
    return dict(acc=(acc_m, acc_s), bal=(bal_m, bal_s),
                fl=(fl_m, fl_s), spread=(sp_m, sp_s))


def f(v, scale=100, nd=1):
    m, s = v
    if m is None:
        return "--"
    return f"{m * scale:.{nd}f}$\\pm${s * scale:.{nd}f}"


def table_tex(task, entries):
    lines = []
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    caption = (f"{task.capitalize()} arithmetic: held-out accuracy ",
               "(mean $\\pm$ std over 3 seeds), balanced accuracy (macro over ",
               "difficulty bins), compute per token, and gate spread ",
               "(hardest minus easiest bin).")
    if task == "tagged":
        caption += (" The ``Ours (Stage-1 = 3K)'' row shows that a 3000-step ",
                    "Stage 1 already costs $\\sim$7 accuracy points on tagged data; ",
                    "the mixed runs use the same shortened Stage 1, which accounts ",
                    "for part of the mixed-regime gap (\\S\\ref{sec:mixed}).")
    lines.append("\\caption{" + "".join(caption) + "}")
    lines.append(f"\\label{{tab:{task}}}")
    lines.append("\\small")
    lines.append("\\begin{tabular}{lcccc}")
    lines.append("\\toprule")
    lines.append("Method & Acc.\\ & Balanced\\ & MFLOPs/tok & Gate spread \\\\")
    lines.append("\\midrule")
    for name, st in entries:
        lines.append(f"{name} & {f(st['acc'])} & {f(st['bal'])} & "
                     f"{f(st['fl'], scale=1, nd=1)} & {f(st['spread'], scale=1, nd=2)} \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    return lines


def main():
    out = ["% auto-generated by paper/generate_tables_raaai.py -- do not edit"]
    text = []

    for task in ("tagged", "mixed"):
        entries = []
        for method, name in METHODS:
            runs = load(f"results/{task}/{method}_seed*.json")
            if runs:
                entries.append((name, row_stats(runs)))
        ours = load(f"results-opt3b-full/{task}/predictor-supervised_seed*.json")
        if task == "tagged":
            tw = load("results-opt3b-s1-5k/tagged/predictor-supervised_seed*.json")
            if tw:
                # headline: Stage-1 = 5K variant; 3K variant kept as ablation row
                entries.append(("\\textbf{Difficulty-supervised (ours)}", row_stats(tw)))
                if ours:
                    entries.append(("Ours (Stage-1 = 3K)", row_stats(ours)))
            elif ours:
                entries.append(("\\textbf{Difficulty-supervised (ours)}", row_stats(ours)))
        elif ours:
            entries.append(("\\textbf{Difficulty-supervised (ours)}", row_stats(ours)))

        out.append(f"\n% ---- {task} ----")
        out += table_tex(task, entries)

        text.append(f"\n== {task} ==")
        for name, st in entries:
            plain = name.replace("\\textbf{", "").replace("}", "").replace("\\", "")
            text.append(f"{plain:32s} acc {f(st['acc']):18s} bal {f(st['bal']):18s} "
                        f"MFLOPs {f(st['fl'], scale=1, nd=1):15s} spread {f(st['spread'], scale=1, nd=2)}")

    # number macros (names contain digits -> define via \csname)
    def mac(name, val):
        return (f"\\expandafter\\newcommand\\csname {name}\\endcsname{{{val}}}")

    with open("results/correlations.json") as fh:
        corr = json.load(fh)["iterations"]
    macros = []
    for key, e in corr.items():
        m, s = ms(e["per_problem_r"])
        tag = key.replace("iter", "Iter").replace("_", "")
        macros.append(mac(f"Corr{tag}", f"{m:.2f}"))

    ours_t = load("results-opt3b-s1-5k/tagged/predictor-supervised_seed*.json")
    if ours_t:
        st = row_stats(ours_t)
        base = row_stats(load("results/tagged/baseline_seed*.json"))
        save = 100 * (1 - st["fl"][0] / base["fl"][0])
        macros.append(mac("OursTaggedAcc", f"{st['acc'][0] * 100:.1f}"))
        macros.append(mac("OursTaggedFlops", f"{st['fl'][0]:.1f}"))
        macros.append(mac("OursTaggedFlopSave", f"{save:.0f}"))
        macros.append(mac("OursTaggedSpread", f"{st['spread'][0]:.2f}"))
    ours_m = load("results-opt3b-full/mixed/predictor-supervised_seed*.json")
    if ours_m:
        st = row_stats(ours_m)
        base = row_stats(load("results/mixed/baseline_seed*.json"))
        save = 100 * (1 - st["fl"][0] / base["fl"][0])
        macros.append(mac("OursMixedAcc", f"{st['acc'][0] * 100:.1f}"))
        macros.append(mac("OursMixedFlops", f"{st['fl'][0]:.1f}"))
        macros.append(mac("OursMixedFlopSave", f"{save:.0f}"))

    with open(os.path.join("paper", "results_raaai.tex"), "w") as fh:
        fh.write("\n".join(out) + "\n")
    print("wrote paper/results_raaai.tex")
    with open(os.path.join("paper", "results_raaai_macros.tex"), "w") as fh:
        fh.write("% auto-generated by paper/generate_tables_raaai.py -- macro half\n")
        fh.write("% (names contain digits; define/use via \\csname)\n")
        fh.write("\n".join(macros) + "\n")
    print("wrote paper/results_raaai_macros.tex")
    print("\n".join(text))
    print("\n".join(macros))


if __name__ == "__main__":
    main()
